"""Crash-safe quota accounting for active objects and SQLite logical content.

A mutation prepares an immutable SQLite generation, commits its exact positive
quota delta in PostgreSQL, then replaces the live file. The journal remains a
reservation until the PostgreSQL counters finalize. A crash cannot expose an
unreserved generation or refund an already accepted write. Filesystem/database
locks are always acquired in global-counter then project order.
"""
from contextlib import closing
import hashlib
import json
import os
from pathlib import Path
import shutil
import sqlite3

from fastapi import HTTPException
from sqlalchemy import select

from app.storage import ProjectStore, DATABASE_NAME, _schema, _connection
from .models import ImageObject, MetadataMutation, Project, UploadReservation, User, identity


def file_hash(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _json_bytes(value):
    return len(json.dumps(value, ensure_ascii=False, allow_nan=False, sort_keys=True,
                          separators=(",", ":")).encode("utf-8"))


def logical_metadata_bytes(path):
    """Canonical user content, excluding filesystem paths and physical indexes.

Each table is a JSON array of canonical records. JSON-valued columns are
counted as objects, never double-escaped text. Source COCO records/masks and
persistent internal/COCO ID mappings count because they occupy durable state.
    """
    total = 2  # enclosing object braces
    with closing(sqlite3.connect(path)) as connection:
        connection.row_factory = sqlite3.Row
        tables = {
            "meta": ("SELECT key,value FROM meta WHERE key IN ('name','coco_metadata') ORDER BY key", {"coco_metadata"}),
            "categories": ("SELECT id,data FROM categories ORDER BY id", {"data"}),
            "images": ("SELECT id,file_name,width,height,sha256,file_size,data,revision,state FROM images ORDER BY id", {"data", "state"}),
            "coco_ids": ("SELECT internal_id,coco_id,image_id FROM coco_ids ORDER BY internal_id", set()),
            "annotation_sources": ("SELECT internal_id,record,mask FROM annotation_sources ORDER BY internal_id", {"record", "mask"}),
        }
        for index, (table, (query, json_columns)) in enumerate(tables.items()):
            total += _json_bytes(table) + 3 + bool(index)  # key, colon, array brackets, comma
            for row_index, row in enumerate(connection.execute(query)):
                record = dict(row)
                for column in json_columns:
                    if table == "meta":
                        if record["key"] == column:
                            record["value"] = json.loads(record["value"])
                    else:
                        record[column] = json.loads(record[column])
                total += _json_bytes(record) + bool(row_index)
    return total


def mutation_directory(settings, mutation_id):
    # IDs are generated by this service and checked before constructing paths.
    from uuid import UUID
    if str(UUID(mutation_id)) != mutation_id:
        raise ValueError("Invalid mutation identity")
    return settings.data_dir / "mutations" / mutation_id


def _durable_file(path):
    with Path(path).open("rb") as source:
        os.fsync(source.fileno())
    descriptor = os.open(Path(path).parent, os.O_RDONLY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _durable_directory_tree(settings, directory):
    """Persist newly created directory entries before PostgreSQL relies on them.

Fsyncing a file and its immediate directory does not persist the parent's
entry for that directory. Include the configured data root's parent because
the root may itself have been created during this process startup.
    """
    directory = Path(directory).resolve()
    boundary = settings.data_dir.resolve().parent
    if not directory.is_relative_to(settings.data_dir.resolve()):
        raise ValueError("Project artifacts must stay inside the data directory")
    directory.mkdir(parents=True, exist_ok=True, mode=0o700)
    current = directory
    while True:
        descriptor = os.open(current, os.O_RDONLY)
        try:
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
        if current == boundary:
            break
        current = current.parent


def _snapshot(source, destination):
    with closing(sqlite3.connect(source)) as original, closing(sqlite3.connect(destination)) as target:
        original.backup(target)
        if target.execute("PRAGMA integrity_check").fetchone()[0] != "ok":
            raise ValueError("Project snapshot failed integrity verification")
    os.chmod(destination, 0o600)


def _initialize_legacy(settings, session, counter, project, objects):
    if project.quota_version == 1 or project.deleted_at:
        return
    path = settings.data_dir / "projects" / project.id / DATABASE_NAME
    metadata = logical_metadata_bytes(path)
    thumbnails = 0
    for image in session.scalars(select(ImageObject).where(ImageObject.project_id == project.id,
                                                          ImageObject.status == "ready")):
        if not objects:
            raise RuntimeError("Object storage is required to migrate active storage quotas")
        image.thumbnail_bytes = len(objects.get(image.object_key.rsplit("/", 1)[0] + "/thumbnail.png"))
        thumbnails += image.thumbnail_bytes
    # Old counters charged exactly the original bytes, so only add omitted data.
    session.get(User, project.user_id).storage_bytes += metadata + thumbnails
    counter.storage_bytes += metadata + thumbnails
    project.metadata_bytes, project.quota_version = metadata, 1


def recover_project_locked(settings, session, counter, project, objects=None):
    """Caller holds global counter + Project FOR UPDATE; commits after return."""
    if project.pending_mutation_id:
        mutation = session.get(MetadataMutation, project.pending_mutation_id)
        if not mutation or mutation.project_id != project.id:
            raise RuntimeError("Project mutation journal is inconsistent")
        target = settings.data_dir / "projects" / project.id / DATABASE_NAME
        staged = mutation_directory(settings, mutation.id) / DATABASE_NAME
        current_hash = file_hash(target) if target.is_file() else None
        if current_hash != mutation.after_sha256:
            if current_hash != mutation.before_sha256:
                raise RuntimeError("Project generation changed unexpectedly; recovery is required")
            if not staged.is_file() or file_hash(staged) != mutation.after_sha256:
                # Never discard an accepted reservation merely because a staged
                # artifact is missing/corrupt. Operator recovery can use backups.
                raise RuntimeError("Reserved project generation is unavailable; recovery is required")
            _durable_directory_tree(settings, target.parent)
            os.replace(staged, target)
            _durable_file(target)
        if logical_metadata_bytes(target) != mutation.new_metadata_bytes:
            raise RuntimeError("Project accounting verification failed")
        if mutation.image_object_id:
            image = session.get(ImageObject, mutation.image_object_id)
            if not image or image.project_id != project.id or image.status != "pending":
                raise RuntimeError("Reserved image registration is inconsistent")
            if image.size_bytes + image.thumbnail_bytes != mutation.object_bytes:
                raise RuntimeError("Reserved object size changed")
            image.status = "ready"
        delta = mutation.new_metadata_bytes - mutation.old_metadata_bytes + mutation.object_bytes
        user = session.get(User, mutation.user_id)
        user.storage_bytes += delta
        counter.storage_bytes += delta
        user.reserved_bytes -= mutation.reserved_bytes
        counter.reserved_bytes -= mutation.reserved_bytes
        project.metadata_bytes = mutation.new_metadata_bytes
        project.pending_mutation_id = None
        project.quota_version = 1
        session.delete(mutation)
    _initialize_legacy(settings, session, counter, project, objects)


def recover_project(settings, db, project_id, objects=None, user_id=None):
    with db.session() as session:
        counter = db.global_lock(session)
        project = session.execute(select(Project).where(Project.id == project_id).with_for_update()).scalar_one_or_none()
        if project is None or (user_id is not None and project.user_id != user_id):
            raise HTTPException(404, "Project not found")
        recover_project_locked(settings, session, counter, project, objects)


def _reserve(settings, user, counter, delta, prior_reservation):
    released = prior_reservation.bytes if prior_reservation else 0
    reserved = max(0, delta)
    # Deletions/reductions remain possible when a migrated account exceeds quota.
    if reserved and user.storage_bytes + user.reserved_bytes - released + reserved > settings.storage_limit_bytes:
        raise HTTPException(413, "Account storage quota exceeded")
    if reserved and counter.storage_bytes + counter.reserved_bytes - released + reserved > settings.global_storage_limit_bytes:
        raise HTTPException(503, "Storage capacity reached")
    user.reserved_bytes += reserved - released
    counter.reserved_bytes += reserved - released
    return reserved


def mutate_project(settings, db, objects, project_id, user_id, callback, *, image_object_id=None,
                   upload_reservation_id=None, create_name=None, cleanup_only=False):
    """Apply callback(ProjectStore, Session, Project) to a staged generation.

The first PostgreSQL transaction commits the journal; the second transaction
finishes it. If either commit response is lost, the staged/live hashes make the
next read or write settle the exact same immutable generation, once.
    """
    if not cleanup_only and settings.min_free_disk_bytes and shutil.disk_usage(settings.data_dir).free < settings.min_free_disk_bytes:
        raise HTTPException(503, "Server storage is temporarily unavailable")
    mutation_id = identity()
    directory = mutation_directory(settings, mutation_id)
    _durable_directory_tree(settings, directory)
    staged = directory / DATABASE_NAME
    try:
        with db.session() as session:
            counter = db.global_lock(session)
            if create_name is not None:
                project = Project(id=project_id, user_id=user_id, name=create_name, metadata_bytes=0, quota_version=1)
                session.add(project)
                session.flush()
                with _connection(staged) as connection:
                    _schema(connection, directory, directory / "unavailable-originals")
                    connection.execute("UPDATE meta SET value=? WHERE key='name'", (create_name,))
                before_hash = None
            else:
                project = session.execute(select(Project).where(Project.id == project_id,
                    Project.user_id == user_id, Project.deleted_at.is_(None)).with_for_update()).scalar_one_or_none()
                if not project:
                    raise HTTPException(404, "Project not found")
                recover_project_locked(settings, session, counter, project, objects)
                session.flush()
                live = settings.data_dir / "projects" / project_id / DATABASE_NAME
                before_hash = file_hash(live)
                _snapshot(live, staged)
            store = ProjectStore(directory)
            result = callback(store, session, project)
            after_bytes, after_hash = logical_metadata_bytes(staged), file_hash(staged)
            object_bytes = 0
            if image_object_id:
                image = session.get(ImageObject, image_object_id)
                if not image or image.project_id != project_id or image.status != "pending":
                    raise HTTPException(409, "Image upload is no longer pending")
                object_bytes = image.size_bytes + image.thumbnail_bytes
            reservation = session.get(UploadReservation, upload_reservation_id) if upload_reservation_id else None
            if upload_reservation_id and (not reservation or reservation.project_id != project_id or reservation.user_id != user_id):
                raise HTTPException(409, "Upload reservation expired")
            delta = after_bytes - project.metadata_bytes + object_bytes
            if cleanup_only and delta > 0:
                raise ValueError("A maintenance cleanup cannot increase logical storage")
            reserved = _reserve(settings, session.get(User, user_id), counter, delta, reservation)
            if reservation:
                session.delete(reservation)
            os.chmod(staged, 0o600)
            _durable_file(staged)
            session.add(MetadataMutation(id=mutation_id, project_id=project_id, user_id=user_id,
                before_sha256=before_hash, after_sha256=after_hash, old_metadata_bytes=project.metadata_bytes,
                new_metadata_bytes=after_bytes, reserved_bytes=reserved, object_bytes=object_bytes,
                image_object_id=image_object_id))
            project.pending_mutation_id = mutation_id
        recover_project(settings, db, project_id, objects, user_id)
        try:
            directory.rmdir()
        except OSError:
            pass  # Cleanup never turns a completed mutation into an API failure.
        return result
    except (HTTPException, ValueError):
        # Validation/quota rejection occurs before the journal transaction
        # commits. If a callback raises after an existing recovery, retain its
        # prior artifacts but remove only this uncommitted staging directory.
        shutil.rmtree(directory, ignore_errors=True)
        raise
    # All other failures intentionally retain the staged file. A COMMIT error
    # does not reveal whether PostgreSQL committed, and deleting it could lose
    # an already accepted write. Reconciliation later handles unused stages.
